[package]
name = "amia-packet"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
byteorder = "1.5.0"
tokio = { version = "1.45.0", optional = true, features = ["net", "io-util"] }

[features]
default = []
kcp = []
tokio = ["dep:tokio"]
